// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::{BamlDecode, __internal::serde::Serialize};
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, BamlDecode, Serialize)]
#[baml(dynamic)]

#[serde(crate = "::baml::__internal::serde")]
pub struct Result {



    pub summary: Option<String>,


    /// Dynamic fields added at runtime via TypeBuilder.
    #[baml(dynamic_fields)]
    #[serde(flatten)]
    pub __dynamic: ::std::collections::HashMap<
        ::std::string::String,
        ::baml::BamlValue<super::super::Types, super::StreamTypes>,
    >,

}


impl Result {
    /// Get a dynamic field by name and convert to the specified type.
    pub fn get<V: ::baml::FromBamlValue<crate::baml_client::types::Types, super::StreamTypes>>(
        &self,
        field: &str,
    ) -> ::std::result::Result<V, ::baml::BamlError> {
        self.__dynamic
            .get(field)
            .cloned()
            .ok_or_else(|| ::baml::BamlError::internal(format!("dynamic field '{}' not found", field)))
            .and_then(|v| v.get())
    }

    /// Get a dynamic field as a BamlValue reference (zero-copy).
    pub fn get_ref(&self, field: &str) -> ::std::option::Option<
        &::baml::BamlValue<crate::baml_client::types::Types, super::StreamTypes>
    > {
        self.__dynamic.get(field)
    }

    /// Check if a dynamic field exists.
    pub fn has(&self, field: &str) -> bool {
        self.__dynamic.contains_key(field)
    }

    /// Iterate over all dynamic fields.
    pub fn dynamic_fields(&self) -> impl ::std::iter::Iterator<Item = (&str, &::baml::BamlValue<crate::baml_client::types::Types, super::StreamTypes>)> {
        self.__dynamic.iter().map(|(k, v)| (k.as_str(), v))
    }
}

impl ::std::default::Default for Result {
    fn default() -> Self {
        Self {

            summary: ::std::default::Default::default(),

            __dynamic: ::std::collections::HashMap::new(),
        }
    }
}


impl ::std::convert::AsRef<Result> for Result {
    fn as_ref(&self) -> &Result {
        self
    }
}

