// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `Result` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

///
/// This class is marked `@@dynamic` - you can add new properties at runtime.

pub struct ResultClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ResultClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("Result is statically defined in .baml and should always have a type")
    }


    /// Add a new property to this dynamic class.
    pub fn add_property(&self, name: &str, field_type: &::baml::TypeDef) -> ::std::result::Result<baml::ClassPropertyBuilder, ::baml::BamlError> {
        self.inner.add_property(name, field_type)
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("Result.summary is statically defined in .baml and should always be present")
    }

}

