// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Embedded BAML source files.

use std::collections::HashMap;
use std::sync::OnceLock;

static FILE_MAP: OnceLock<HashMap<String, String>> = OnceLock::new();

/// Get the embedded BAML source files.
pub fn get_baml_files() -> &'static HashMap<String, String> {
    FILE_MAP.get_or_init(|| {
        let mut m = HashMap::new();

        m.insert("clients.baml".to_string(), "client<llm> CustomGemini {\r\n  provider google-ai\r\n  options {\r\n    model \"gemini-3.6-flash\"\r\n    api_key env.GOOGLE_API_KEY\r\n  }\r\n}\r\n".to_string());

        m.insert("generated_ontology.baml".to_string(), "class Result {\r\n  summary string\r\n  @@dynamic  // Dynamic nodes and edges will be injected here\r\n}\r\n\r\nfunction ExtractInfo(input: string) -> Result {\r\n  client \"CustomGemini\"\r\n  prompt #\"\r\n    Extract structured information from the following text based on the requested schema.\r\n\r\n    {{ ctx.output_format }}\r\n\r\n    {{ _.role(\"user\") }} {{ input }}\r\n  \"#\r\n}".to_string());

        m.insert("generators.baml".to_string(), "// This helps use auto generate libraries you can use in the language of\r\n// your choice. You can have multiple generators if you use multiple languages.\r\n// Just ensure that the output_dir is different for each generator.\r\ngenerator target {\r\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\r\n    output_type \"rust\"\r\n\r\n    // Where the generated code will be saved (relative to baml_src/)\r\n    output_dir \"../\"\r\n\r\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\r\n    // The BAML VSCode extension version should also match this version.\r\n    version \"0.225.0\"\r\n\r\n    // Valid values: \"sync\", \"async\"\r\n    // This controls what `b.FunctionName()` will be (sync or async).\r\n    default_client_mode sync\r\n}\r\n".to_string());

        m
    })
}